name: Auto-merge Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build:
    uses: ./.github/workflows/ci.yml

  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'RIPE-NCC/rpki-commons'
    steps:
      - name: Fetch Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v2
        with:
          alert-lookup: true
          compat-lookup: true
          github-token: "${{ secrets.GITHUB_TOKEN }}"
        
      - name: Check if PR is ready for auto-merge
        id: check-pr
        run: |
          # Test with dependabot metadata if available, otherwise use title
          if [[ "${{ steps.dependabot-metadata.outputs.update-type }}" == "version-update:semver-patch" ]] || \
             [[ "${{ steps.dependabot-metadata.outputs.update-type }}" == "version-update:semver-minor" ]] || \
             [[ "${{ github.event.pull_request.title }}" =~ (patch|minor) ]]; then
            # echo "auto_merge=true" >> $GITHUB_OUTPUT
            echo "auto_merge=true"
          else
            # echo "auto_merge=false" >> $GITHUB_OUTPUT
            echo "auto_merge=false"
          fi       

      - name: Enable auto-merge
        if: steps.check-pr.outputs.auto_merge == 'true'
        run: |
          # gh pr merge ${{ github.event.pull_request.number }} --auto --squash
          echo "gh pr merge ${{ github.event.pull_request.number }} --auto --squash"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Approve PR
        if: steps.check-pr.outputs.auto_merge == 'true'
        run: |
          # gh pr review ${{ github.event.pull_request.number }} --approve
          echo "gh pr review ${{ github.event.pull_request.number }} --approve"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}