#
# based on https://github.com/actions/setup-java
#
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_call:
    outputs:      
      test-reports:
        description: "Name of the test reports artifact."
        value: "test-results"    

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    strategy:
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [ 11, 17, 21 ]
    name: Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache maven artifacts
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-${{ matrix.java }}-${{ hashFiles('**/pom.xml') }}

      - name: Setup java
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      - name: Build with Maven
        run: mvn -B verify --file pom.xml
      - name: Archive test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-results
          path: |
            target/surefire-reports/
      - name: Publish Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1 
