name: release

on:
  push:
    branches: [ main, add-release-action ]
    # tags: 'rpki-commons-*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare environment
        run: |             
            sudo apt-get install rsync git gnupg

      - name: Checkout Code
        uses: actions/checkout@v3.2.0

      - name: Setup Java
        uses: actions/setup-java@1.4.3
        with:
          java-version: 8

      - name: Release
        env: 
          GPG_PASSPHRASE: "bla"
          SCM_DEVELOPER_URL: "blabla"          
        run: |       
          # checking GPG signing support
          if [ -n "$GPG_KEY" ]; then
            echo "$GPG_KEY" | gpg --batch --no-tty --allow-secret-key-import --import -
            unset GPG_KEY
            export GPG_KEYID=$(gpg --with-colon --list-secret-keys | head -n1 | cut -d : -f 5)

            # GPG stuff works, do the release
            export MAVEN_OPTS="-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$HOME/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"   
            mvn versions:set -DnewVersion=$(echo ${GITHUB_REF#refs/*/} | sed -e 's/rpki-commons-//')
            mvn $MAVEN_CLI_OPTS deploy -s ci_settings.xml -P default,release
            echo "done"
          else
            echo -e "\033[0;31m****** GPG signing disabled ******\033[0m"
          fi        
          