name: release

on:
  push:
    branches: [ main, add-release-action ]
    # tags: 'rpki-commons-*'

jobs:
  build:
    runs-on: maven:3.6-jdk-8-alpine

    steps:
      - name: Prepare environment
        run: |             
            apk update && apk add rsync git gnupg

      - name: Checkout Code
        uses: actions/checkout@v2.3.4

      - name: Setup Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 8

      - name: Release
        run: |       
          MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"   
          mvn versions:set -DnewVersion=$(echo ${GITHUB_REF#refs/*/} | sed -e 's/rpki-commons-//')
          mvn $MAVEN_CLI_OPTS deploy -s ci_settings.xml -P default,release
          echo "done"